### PR TITLE
Implement ES6 modules - Fixes #210

### LINKED ISSUE #210: Use ES6 modules + Rollup
As the front-end world rapidly moves to ES6-compatible bundling, simple-statistics could really benefit from switching from CommonJS to ES6 modules and Rollup. It may introduce small additional set up for tests and NPM prepublish scripts, but advantages now overweight the cons IMO. The library will especially benefit from tree-shaking (also see #180), leaner browser builds, and being future-proof.

SS would still have a CommonJS-compatible entry point for Node, but additionally use `pkg.module` for ES6-aware consumers. The Webpack code splitting issues should not hold us back because they're not ES6-specific, and are probably still a problem when you try to set up code splitting with CommonJS modules. 

Examples of other libraries that switched happily to Rollup include React, Vue, Ember, Preact, D3, Three.js, Moment and PouchDB.

cc @tmcw @Yomguithereal

### PR DESCRIPTION
**Pull request by DenisCarriere**
## Implementation of ES6 modules 💥 🎉 

Ref: https://github.com/simple-statistics/simple-statistics/issues/210

- [x] Include Rollup configuration to `dist/simple-statistics.js`
- [x] Add source mapping & minify directly in Rollup config (1.5s to build Rollup bundle)
- [x] Documentation JSDocs test
- [x] Replaced Browserify + minify with Rollup
- [x] Convert all source code to ES6 export/import
- [x] Convert tests to use main library `var ss = require('../')`
- [x] Dropped `"use strict"` (unnecessary inside of modules)
- [x] Fix JSDocs linting issues
- [x] Dropped `.npmignore` (not required if you include `files` in `package.json`)

Tons of changes, but it's really not too bad to review, I've made sure to only change what's needed to make the ES6 module implementation.

Rollup config & module export syntax was inspired by @mbostock's [`d3-geo-projection`](https://github.com/d3/d3-geo-projection).

CC: @mourner @tmcw

### CODE REVIEW

**Comment by tmcw** [comment]
Wow, awesome :) This would probably be a 5.x, because many simple-statistics users use `require('simple-statistics/min')` and other sub-requires to get just one module, whereas now they will always import `simple-statistics` but possibly only some of its bindings.

I think the only thing to nail down here is the removal of jsdoctest - that project was unfortunately [stalled for a while, but has a new release](https://github.com/yamadapc/jsdoctest/issues/33), but does this mean that... it wouldn't support ES6?

**Comment by DenisCarriere** [comment]
👍 Thanks 😄 

> This would probably be a 5.x

Agreed, changing the library entirely to ES6 modules will break some minor things such `require('simple-statistics/min')` since `min.js` will now contain `export default`.

**Before**

```js
const min = require('simple-statistics/min');
```

**Now ES6**

```js
import { min } from 'simple-statistics';
```

**Now CommonJS**

```js
const min = require('simple-statistics').min;
```

> I think the only thing to nail down here is the removal of jsdoctest 

Ops! Didn't realize I removed `jsdoctest`, I'll look into re-implementing it, I don't see why it shouldn't work... 🤔

**Comment by DenisCarriere** [comment]
# JSDoctest Update

Got it to work using `mocha --require jsdoctest dist/index.js`, I simply added a CommonJS build to the Rollup config. Currently there's 3 Rollup outputs (UMD, UMD + minified & CommonJS) all with sourcemaps.

**Comment by DenisCarriere** [comment]
## Rollup Config

Here's the latest `rollup.config.js`, made it more "compact" by adding default settings and it's now way easier to read/understand.

```js
import uglify from 'rollup-plugin-uglify';

function assign({ file, format, plugins }) {
    return {
        input: 'index',
        output: {
            file,
            format: format || 'umd',
            extend: true,
            sourcemap: true,
            name: 'ss'
        },
        plugins: plugins || []
    }
}
export default [
    assign({ file: 'dist/simple-statistics.js' }),
    assign({ file: 'dist/simple-statistics.min.js', plugins: [uglify()] }),
    assign({ format: 'cjs', file: 'dist/index.js' })
];
```

**Comment by DenisCarriere** [comment]
👍 🎉 Woot!

@tmcw Feel free to refactor it to your likings, many options are viable.

**Pull request merged**
